// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urfddpxffsrvwsucbgwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZmRkcHhmZnNydndzdWNiZ3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTMxMDUsImV4cCI6MjA3MDQ4OTEwNX0.W-so_G7CoEogH5Pta0m1GkJeD7HS1yFEeR2Jdw_1etQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});